In [1]:
import pandas as pd
df = pd.read_csv("usarrests.csv")
df.describe()

         Murder     Assault   UrbanPop
count  50.00000   49.000000   50.00000
mean    7.78800  182.183673   74.20000
std     4.35551  130.877435   73.40828
min     0.80000   45.000000    6.00000
25%     4.07500  109.000000   53.25000
50%     7.25000  159.000000   66.00000
75%    11.25000  249.000000   77.75000
max    17.40000  879.000000  570.00000

In [2]:
df[df["Assault"].isna()]

  Unnamed: 0  Murder  Assault  UrbanPop
9    Georgia    17.4      NaN        60

In [3]:
#The value is missing, since there is no value to assign to it. I would put the median for the assault

In [4]:
fill_value = df["Assault"].median()
df["Assault"] = df["Assault"].fillna(fill_value)

In [5]:
df[df["Assault"].isna()]

Empty DataFrame
Columns: [Unnamed: 0, Murder, Assault, UrbanPop]
Index: []

In [6]:
df[df["UrbanPop"] > 100]

   Unnamed: 0  Murder  Assault  UrbanPop
14       Iowa     2.2     56.0       570

In [7]:
#The urban population is impossible. It cannot be more than 100. I think it is an error, instead of 570 it
# should be 57

In [8]:
df[df["Assault"] > 249]

        Unnamed: 0  Murder  Assault  UrbanPop
1           Alaska    10.0    263.0        48
2          Arizona     8.1    294.0        80
4       California     9.0    276.0        91
8          Florida    15.4    335.0        80
19        Maryland    11.3    300.0        67
21        Michigan    12.1    255.0        74
23     Mississippi    16.1    259.0        44
27          Nevada    12.2    252.0        81
30      New Mexico    11.4    285.0        70
31        New York    11.1    254.0         6
32  North Carolina    13.0    337.0        45
39  South Carolina    14.4    879.0        48

In [9]:
#The assualt number for South Carolina is higher than it should be. It is more than 2 times higher than
#the next closests number. As well as way higher than states with a higher urban population.
#I would say this number is extreme. I would use the median for the assault number as well.