In [4]:
import pandas as pd
from sklearn.linear_model import LinearRegression
df = pd.read_csv("ratings.tsv", sep="\t")
df.head()

   restaurant  food  ambience  service  rating
0           1    85        82       89      78
1           2    80        90       80      85
2           3    83        86       83      85
3           4    70        96       75      72
4           5    68        80       78      75

In [6]:
features = ["ambience", "food", "service"]
x = df[features]
y = df["rating"]
model = LinearRegression()
model.fit(x,y)
print("Intercept:", round(model.intercept_, 3))
print("Coefficients:", model.coef_.round(3))
print("R2:", round(model.score(x,y), 3))

Intercept: -15.871
Coefficients: [0.134 0.734 0.324]
R2: 0.794

In [10]:
coefs = (pd.DataFrame({"feature": features, "coefficient":model.coef_})
.sort_values("coefficient", ascending=False)
.reset_index(drop=True))
coefs["coefficient"] = coefs["coefficient"].round(3)
coefs.index += 1
coefs

    feature  coefficient
1      food        0.734
2   service        0.324
3  ambience        0.134

In [ ]:
#Improving the food rating should be the most important rating. It has the most points associated with
#the overall rating.